### ISSUE TITLE
OK to register?

### ISSUE THREAD

**Issue by timholy** [JuliaCollections/LeftChildRightSiblingTrees.jl#1]
Do the other JuliaCollections folks think this is ready to register as a package?

**Comment by oxinabox** [comment]
I will review within the hour.

**Comment by oxinabox** [comment]
Looks good to me.

 - CI is enabled, 
 - there is nothing aweful in the package or its tests.
 - Liscense is there
 - Project.toml looks right.

I think readme needs an example, but that can be after registration is submitted.
See #2 

I note that you did not preserve the git history, but I don't think thats really a problem.
If you did want to change that though, this is the last chance since doing it after registration is frustrating since it chances all the commit SHAs.

I recall seeing this in one of your packages (now the read me tells me which) and thinking "that really should be in a JuliaCollectionsPackage.

I guess also it is worth thinking about if this should be called `Trees.jl` so to take on extras later.
I am figuring you have considered that and decided not to.
Which is reasonable.

**Comment by timholy** [comment]
Yes, there are so many potential different implementations of trees, we almost might want a sub-organization called JuliaTrees. Though not many well-maintained implementations are out there (somewhat surprisingly).

I'm not really that worried about the git history, it would be complex to get it right. (This portion of ProfileView hasn't changed in ages, so very few commits would have been relevant.)

**Comment by timholy** [comment]
Closed by https://github.com/JuliaRegistries/General/pull/7815
